### ISSUE TITLE
Alternative instance MonadState s (ContT r m)

### ISSUE THREAD

**Issue by AshleyYakeley** [ekmett/mtl#16]
I notice that instead of requiring `MonadState s m`, it's possible to require `MonadReader s m`:

    instance MonadReader s m => MonadState s (ContT r m) where
        get = ContT (\smr -> ask >>= smr)
        put s = ContT (\umr -> local (\_ -> s) (umr ()))

Is this preferable?

**Comment by ekmett** [comment]
This would violate user expectation somewhat severely.

**Comment by AshleyYakeley** [comment]
Just as a datapoint, it happened to be the instance I wanted, inasmuch as `MonadReader` is "simpler" than `MonadState`: indeed you can kinda/sorta make `MonadReader` a superclass of `MonadState`, though I'm not actually proposing this.

    instance MonadReader s m where
        ask = get
        -- | imperfect, but you get the idea
        local ss ma = do
            s <- get
            put (ss s)
            a <- ma
            put s
            return a

**Comment by ekmett** [comment]
Reader and State do have a sort of incestuous relationship.

`Codensity (Reader s) ~ State s`, because State is made up of the composition of Reader s and its adjoint functor: `(, s)`. Using this you can always embed reader effects into State.

In an almost equally universal manner you can embed writer effects into state, but there are some minor complications on that front, and while the reader embedding costs you commutativity the latter costs you productivity.

**Comment by treeowl** [comment]
Would it be worth the trouble to come up with a `ContT` wrapper offering this instance?

**Comment by ekmett** [comment]
Possibly. If so it should belong in `transformers` though, not `mtl`, and then `mtl` would inherit support for it.
