### ISSUE TITLE
Cont instances for StateT

### ISSUE THREAD

**Issue by ivan-m** [ekmett/mtl#19]
The `MonadCont` for both Lazy and Strict `StateT` uses `liftCallCC'` from their respective modules.

However, if you look at the documentation for these functions, they both say:

> It does not satisfy the laws of a monad transformer.

(As opposed to `liftCallCC`, which presumably does.)

Is the documentation for `liftCallCC'` incorrect (in which case this is something that should be fixed in `transformers`), or is mtl really using a function that prevents the monad transformer laws from being satisfied?

(This is [also true](http://hackage.haskell.org/package/mtl-1.1.1.1/docs/src/Control-Monad-State-Lazy.html) in pre-transformers mtl, so it's highly possible that the behaviour was just copied over.  The comment about not satisfying the monad transformer laws was not added until `transformers-0.2.0.0`... which is also the first version of transformers used by mtl.)

**Comment by ekmett** [comment]
This behavior is considered "by design" and historical. Changing it isn't a viable option. 

The desirability of a "uniform lifting property" for `liftCallCC` was retroactively added after the fact, and there is no migration plan that doesn't just silently change semantics on almost every piece of user code written using `Cont`.

We carefully document that we do not have this desirable property on this instance for this reasoning.
