### ISSUE TITLE
No MonadError instance for Maybe or []

### ISSUE THREAD

**Issue by jason-johnson** [ekmett/mtl#27]
There is a MonadError instance defined for Either, but neither Maybe nor List ([]) even though the transformer versions of those types *are* defined.

As it stands, users who may wish to treat a failure as a Nothing or empty list must define Orphaned instances.

**Comment by ekmett** [comment]
`MonadError` implies two things:

1.) The type of error is determined by the monad.
2.) You can `catchError` whatever it is that you throw with `throwError`.

Neither one of these properties holds for either `Maybe` or `List`. 

You can't just make `instance MonadError e Maybe` because of the functional dependency.

They can't comply with the `MonadError` invariants unless the 'e' in `MonadError` is `()`.

I have no particular objection to adding this very restricted instance for each, but note as described above it can't be "whatever error type you want to throw", it can only be `()`.

**Comment by ekmett** [comment]
On the other-other hand, these instances are inconsistent with the behavior of `MaybeT` and `ListT`.

**Comment by ekmett** [comment]
Deciding not to proceed here because of the incompatibility with the existing `MaybeT` and `ListT` instances.

**Comment by Ericson2314** [comment]
Sorry what's the incompatibility/inconsistency with `MaybeT`?

**Comment by ekmett** [comment]
The instance for MaybeT lifts the MonadError instance for the underlying monad. 

```haskell
instance MonadError e m => MonadError e (MaybeT m)
```

Having `Maybe` and `MaybeT Identity` have different semantics would be very awkward.

**Comment by Ericson2314** [comment]
Ah of course, thanks. Maybe it's just best to add a `catchM` to `transformers` then.
